### ISSUE TITLE
T5: Als Nutzer möchte ich Vorlesungen anlegen und diesen ein Verständnisgrad zuweisen können, um einen Überblick über den Nachholbedarf von  Vorlesungsthemen zu behalten

### ISSUE THREAD

**Issue by 0xfr34ky** [nils-imhoff/projektmanagement#9]
Card “Alle Vorlesungen” erstellen
Menüeintrag “Vorlesungen” erstellen
Button “Neue Vorlesung” erstellen
Card “Neue Vorlesung” erstellen
Formular mit Vorlesungsbezeichnung erstellen
Funktion zur Erstellung der Vorlesung anlegen

**Comment by phisinger** [comment]
Task done.
